name: Minify JavaScript

on: [push]

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Terser
      run: npm install -g terser

    - name: Minify JavaScript files
      run: find . -name '*.js' ! -name '*.min.js' -exec terser {} -c -m -o {}.min \;

    - name: Rename minified JavaScript files
      run: find . -name '*.js.min' -exec bash -c 'mv "$0" "${0/.js.min/.min.js}"' {} \;

    - name: Commit minified files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Minify JavaScript files
        file_pattern: '*.min.js'
