name: Minify JavaScript

on: [push]

permissions:
  contents: write

jobs:
  minify:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Terser
      run: npm install -g terser

    - name: Minify JavaScript files
      run: find . -name '*.js' ! -name '*.min.js' -exec terser {} -o {}.min \;

    - name: Remove original JavaScript files
      run: find . -name '*.js' ! -name '*.min.js' -exec rm {} \;

    - name: Rename minified JavaScript files
      run: find . -name '*.js.min' -exec rename 's/\.js\.min$/.js/' {} \;

    - name: Commit minified files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Minify JavaScript files
